spack:
  specs:
  - root@6.22.08 +davix+gsl+math~memstat+minuit+mlp~mysql+opengl~postgres~pythia6+pythia8+python~qt4+r+root7+roofit+rpath~shadow+sqlite+ssl~table+tbb+threads+tmva+unuran+vc+vdt+vmc+x+xml+xrootd
  - delphes@master
  - python
  - py-pyyaml
  - py-jinja2
  - pythia8
  - evtgen
  - hepmc@2.06.10
  - cmake
  view: true
  concretization: together
  packages:
    all:
      compiler: [gcc@9.3.0]
      variants: [cxxstd=17]
